In [3]:
import numpy as np
import random

#konstruisanje matrice H LDPC koda

n = 15 
k = 6  
wc = 3 #kolona
wr = 5 #red

random.seed(98,2018)

#n - k = 9

H = np.zeros((n-k, n), dtype=int)

for i in range(wc): H[i, i * wr : i * wr + 5] = 1

for i in range(wc, n-k):
    count = 0
    while count < wr:
        slobodno = [col for col in range(n) if np.sum(H[:, col]) < wc]
        if len(slobodno) == 0:
            break
        trenutnaKolona = np.random.choice(slobodno, 1)[0]
        if H[i, trenutnaKolona] == 0:
            H[i, trenutnaKolona] = 1
            count += 1

print("--- H MATRICA ---\n")
print(H)


--- H MATRICA ---

[[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
 [1 0 0 0 1 0 0 1 0 1 0 0 1 0 0]
 [1 0 0 0 1 0 0 0 0 1 0 0 0 1 1]
 [0 1 1 0 0 1 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 1 0 1 0 1 1 0 0 0]
 [0 0 0 1 0 0 0 1 1 0 0 1 0 1 0]
 [0 1 1 1 0 0 0 0 0 0 1 0 1 0 0]]


In [4]:
import numpy as np

#generisanje tabele korektora i sindroma

k = H.shape[0]  
n = H.shape[1] 

br_gresaka = 2 ** n  

sviKorektori = []

for i in range(br_gresaka):
    vektor = tuple(int(bit) for bit in np.binary_repr(i, n))
    sviKorektori.append(vektor)

sortiraniKorektori = sorted(sviKorektori, key=lambda x: sum(x))
matricaKorektora = np.array(sortiraniKorektori)

rezultati = np.mod(np.dot(H, np.array(matricaKorektora).T), 2).T

elementi, ind = np.unique(rezultati, axis=0, return_index=True)

korektori = [sortiraniKorektori[i] for i in ind]

print("TABELA KOREKTORA: \tTABELA SINDROMA:")
for indeks, (element, korektor) in enumerate(zip(elementi, korektori)):
    print(f"{element} : {korektor}")

#odredjivanje kodnog rastojanja

niz_matrica = []
br_kolona = []
broj_kolona_parnih = []

def parnost_reda(matrix):
    return [sum(red) % 2 for red in matrix] if ([sum(red) % 2 for red in matrix] != [0]*9) else (broj_kolona_parnih.append(len(matrix[0])) or [0]*9)

sviKorektori = np.array(sviKorektori)
matrica_H = np.array(H)

for k in sviKorektori:
    temp = [matrica_H[:, idx] for idx, bit in enumerate(k) if bit]
    temp = np.array(temp).T
    niz_matrica.append(temp)
    br_kolona.append(temp.shape[1] if temp.ndim == 2 else 1)

for i, (m, clan, broj) in enumerate(zip(niz_matrica, sviKorektori, br_kolona)):
    zbir_redova = parnost_reda(m)
print("\n")
print("Kodno rastojanje:", min(broj_kolona_parnih))







TABELA KOREKTORA: 	TABELA SINDROMA:
[0 0 0 0 0 0 0 0 0] : (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
[0 0 0 0 0 0 0 1 1] : (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0)
[0 0 0 0 0 0 1 0 1] : (0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0)
[0 0 0 0 0 0 1 1 0] : (0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0)
[0 0 0 0 0 1 0 0 1] : (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1)
[0 0 0 0 0 1 0 1 0] : (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1)
[0 0 0 0 0 1 1 0 0] : (0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1)
[0 0 0 0 0 1 1 1 1] : (0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1)
[0 0 0 0 1 0 0 0 1] : (0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0)
[0 0 0 0 1 0 0 1 0] : (0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0)
[0 0 0 0 1 0 1 0 0] : (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0)
[0 0 0 0 1 0 1 1 1] : (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0)
[0 0 0 0 1 1 0 0 0] : (0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1)
[0 0 0 0 1 1 0 1 1] : (0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0)
[0 0 0 0 1 1

In [6]:
#implementacija Gallager B algoritma

def gallager_b_dekodiranje(input, th_0=0.5, th_1=0.5, maxIter=100):
    duzinaInput = len(input)
    dekodirano = list(input)

    for i in range(maxIter):
        for ind in range(duzinaInput):
            for k in range(duzinaInput):
                if k != ind:
                    sumaSuseda = sum(dekodirano) - dekodirano[ind]
                    primljeneVrednosti = [sumaSuseda for _ in range(duzinaInput) if _ != ind]
                    
                    brojNula = primljeneVrednosti.count(0)
                    brojJedinica = primljeneVrednosti.count(1)
                    dekodirano[ind] = 0 if brojNula >= th_0 * (duzinaInput - 1) else 1 if brojJedinica >= th_1 * (duzinaInput - 1) else int(input[ind])

        if all(dekodirano[k] == int(input[k]) for k in range(duzinaInput)):
            print(f"Dostignuto stacionarno stanje u  {i + 1} iteraciji.")
            break

    return dekodirano


input = [1, 0, 0, 0, 0, 0, 0]
dekodirano = gallager_b_dekodiranje(input)
print("Dekodirano: \n")
print(dekodirano)



Dekodirano: 

[0, 0, 0, 0, 0, 0, 0]
